export const FETCH_VIDEOS_ATTEMPT = 'FETCH_VIDEOS_ATTEMPT';
export const FETCH_VIDEOS_SUCCESS = 'FETCH_VIDEOS_SUCCESS';
export const FETCH_VIDEOS_FAIL = 'FETCH_VIDEOS_FAIL';
export const SELECT_VIDEO = 'SELECT_VIDEO';

